import style from './style.module.css';
import About from '../sections/About/About'
import Teams from '../sections/Teams/Teams'
import Services from '../sections/Services/Services'
import SelectCar from '../sections/SelectCar/SelectCar'
import Brands from '../sections/Brands/Brands';
import Contacts from '../sections/Contacts/Contacts';

export const metadata = {
  title: "О нас",
  description: "Generated by create next app",
};

export default function Page() {
    return (
        <section className={style.about}>
            <div className="container">
                <h2 className={style.title}>О <span>нас</span></h2>
            </div>
            <About />
            <Teams />
            <Services />
            <SelectCar />
            <section className="brand-swipper">
                <div className="container">
                    <Brands />
                </div>
            </section>
            <Contacts />
        </section>
    );
}