import { Clock4, Mail, MapPin, Phone } from 'lucide-react';
import style from './style.module.css';
import Offer from '../sections/Offer/Offer'
import Brands from '../sections/Brands/Brands'
import Contacts from '../sections/Contacts/Contacts'

export const metadata = {
  title: "Контакти",
  description: "Generated by create next app",
};


export default function Page() {

    return (
        <section className={style.contacts}>
            <div className="container">
                <h2 className={style.title}>Наші <span>контакти</span></h2>
                <div className={style['contacts-wrapper']}>
                    <div className={style['contacts-info']}>
                        <Mail size={48} />
                        <p className={style['contacts-title']}>email</p>
                        <p>test@gmail.com</p>
                    </div>
                    <div className={style['contacts-info']}>
                        <MapPin size={48} />
                        <p className={style['contacts-title']}>адреса</p>
                        <p>test@gmail.com</p>
                    </div>
                    <div className={style['contacts-info']}>
                        <Phone size={48} />
                        <p className={style['contacts-title']}>телефон</p>
                        <p>test@gmail.com</p>
                    </div>
                    <div className={style['contacts-info']}>
                        <Clock4 size={48} />
                        <p className={style['contacts-title']}>час роботи</p>
                        <p>test@gmail.com</p>
                    </div>
                </div>
                <div className={style['contacts-form-title']}>Пішить нам</div>
                <div className={style['contacts-wrapper-form']}>
                    <div className={style.form}>
                        <form action="" className={style['contacts-form']}>
                            <input type="text" placeholder='Ім’я' className={style['contacts-item']} />
                            <input type="text" placeholder='Email' className={style['contacts-item']} />
                            <input type="text" placeholder='Телефон' className={style['contacts-item']} />
                            <textarea rows='30' className={style['contacts-item']}></textarea>
                            <button className={style.btn}>Відправити</button>
                        </form>
                    </div>
                    <div className="">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto aliquid saepe suscipit dignissimos cum fugit impedit error exercitationem nemo at?
                    </div>
                </div>
            </div>
            <Offer />
            <section className="brand-swipper">
                <div className="container">
                    <Brands />
                </div>
            </section>
            <Contacts />
        </section>
    );
}