import style from './style.module.css';
import LoginForm from '../components/LoginForm/LoginForm'

export const metadata = {
  title: 'Вхід',
  description: "Generated by create next app",
};

export default function Page() {

    return (
        <section className={style.login}>
            <LoginForm />
        </section>
    );
}