import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import Auth from './context/Auth'
import { getServerSession } from "next-auth";
import { ToastContainer } from "react-toastify";

const rubik = Rubik({
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: 'LuxRental - Premium Cars',
    template: '%s | LuxRental - Premium Cars'
  },

  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const session = getServerSession()

  return (
    <html lang="en">
      <body className={rubik.className}>
        <ToastContainer theme="light" autoClose={2000} position="bottom-right" />
        <Auth session={session}>
          <div className="main">
            <Header />
            <main>
              {children}
            </main>
            <Footer />
          </div>
        </Auth>
      </body>
    </html>
  );
}
