import Brands from "../sections/Brands/Brands";
import Contacts from "../sections/Contacts/Contacts";
import Services from "../sections/Services/Services";
import Offer from '../sections/Offer/Offer'
import style from './style.module.css';

export const metadata = {
  title: "Сервіси",
  description: "Generated by create next app",
};

export default function Page() {
    return (
        <section className={style.services}>
            <div className="container">
                <h2 className={style.title}>Наші <span>сервіси</span></h2>
            </div>
            <Services />
            <Offer />
            <section className="brand-swipper">
                <div className="container">
                    <Brands />
                </div>
            </section>
            <Contacts />
        </section>
    );
}