import React from 'react';
import style from './style.module.css';
import BlogCard from '../components/BlogCard/BlogCard'

export const metadata = {
  title: "Блог",
  description: "Generated by create next app",
};

const Page = async () => {

    const res = await fetch('http://localhost:3000/api/blogs', { cache: 'no-store' })
    const blogList = await res.json()

    return (
        <section className={style.blog}>
            <div className="container">
                <h2 className={style.title}>Наш <span>блог</span></h2>
                <div className={style['blog-wrapper']}>
                    {blogList.map(item => (
                        <BlogCard {...item} />
                    ))}
                </div>
            </div>
        </section>
    );
}

export default Page;
