import style from './style.module.css';
import CarsList from '../sections/CarsList/CarsList'
import Offer from '../sections/Offer/Offer'
import Brands from '../sections/Brands/Brands'
import Contacts from '../sections/Contacts/Contacts'

export const metadata = {
  title: "Машини",
  description: "Generated by create next app",
};

export default function Page() {
    return (
        <section className={style.cars}>
            <div className="container">
                <h2 className={style.title}>Наш <span>автопарк</span></h2>
                <CarsList />
            </div>
            <Offer />
            <section className="brand-swipper">
                <div className="container">
                    <Brands />
                </div>
            </section>
            <Contacts />
        </section>
    );
}